const productsData = [
  {
    id: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4P5cNgyzPtIdIuER6ywBuFLB6347LXw4_ig&usqp=CAU",
    title: "Headphones",
    description: "Very cool looking headphones",
    price: 34,
    category: "electronics",
  },
  {
    id: 2,
    img: "https://dcassetcdn.com/design_img/3531403/71684/71684_19414064_3531403_7cc1925b_image.jpg",
    title: "T-shirt",
    description: "Comfortable and stylish cotton t-shirt",
    price: 20,
    category: "clothing",
  },
  {
    id: 3,
    img: "https://www.seriouseats.com/thmb/1ks2L6lZZS-H2gjdhfzqAnVAbBs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Web_1500-SEA_NespressoReview_AshleyRodriguez_74-bea97ecd763e4547874c8f571242c1a1.jpg",
    title: "Coffee Maker",
    description: "Modern coffee maker for the perfect brew",
    price: 50,
    category: "home and kitchen appliances",
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/61GoBXXF8iL.jpg",
    title: "Moisturizing Shampoo",
    description: "Revitalize your hair with this nourishing shampoo",
    price: 15,
    category: "health and beauty",
  },
  {
    id: 5,
    img: "https://woodentwist.com/cdn/shop/products/WhatsAppImage2023-03-23at1.53.07AM_512x512.jpg?v=1689878388",
    title: "3-Seater Sofa",
    description: "Elegant and comfortable sofa for your living room",
    price: 300,
    category: "furniture and home decor",
  },
  {
    id: 6,
    img: "https://amaron-prod-images.s3.ap-south-1.amazonaws.com/styles/product_detail_img_450x350/s3/product-front-image/AAM-FL-545106036.jpg?itok=8fvfto1Z",
    title: "Car Battery",
    description: "Reliable battery for various vehicle models",
    price: 100,
    category: "automotive and tools",
  },
  {
    id: 7,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0I_2K8DINTwGxDnNU48Tii-cUFkc40GmkBQ&usqp=CAU",
    title: "Bestseller Novel",
    description: "Exciting fiction novel for your reading pleasure",
    price: 12,
    category: "books and media",
  },
  {
    id: 8,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLCYAi8HITcs0LYz9MsjMdHWBqaaMhzN63yg&usqp=CAU",
    title: "Strategy Board Game",
    description: "Engaging game to challenge your tactical skills",
    price: 30,
    category: "toys and games",
  },
  {
    id: 9,
    img: "https://media.istockphoto.com/id/142533334/photo/yellow-dome-tent-with-open-zip-enclosure.jpg?s=612x612&w=0&k=20&c=GZyiiSF95j0Yxa_7pc6LUebf8MVvRebJcrnMXETN5eU=",
    title: "Camping Tent",
    description: "Spacious tent for your outdoor adventures",
    price: 120,
    category: "sports and outdoors",
  },
  {
    id: 10,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTakTkEb_JvT2V8xHOH09MRG7WKFWxZKh_sLdxMSRi_LMcOAsqKtKmCgsBcHmkFC2zxdDc&usqp=CAU",
    title: "Diamond Ring",
    description: "Exquisite diamond ring for special occasions",
    price: 500,
    category: "jewelry and accessories",
  },
  {
    id: 11,
    img: "https://hips.hearstapps.com/hmg-prod/images/mower-1568302588.jpg?crop=1.00xw:0.669xh;0,0.318xh&resize=1200:*",
    title: "Lawn Mower",
    description: "Efficient lawn mower for garden maintenance",
    price: 250,
    category: "gardening and outdoor living",
  },
  {
    id: 12,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1XBW1qmd1eznAFhjnE60rZmdTcitmEOgrQQ&usqp=CAU",
    title: "Interactive Dog Toy",
    description: "Keeps your pet entertained and active",
    price: 18,
    category: "pet supplies",
  },
  {
    id: 13,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqd0f9aV6kIawryr3-cqJhcLIpbDwOFqJnXLkcjAJAy9l_DoGVvpdxgQMHLfUsP19zXlQ&usqp=CAU",
    title: "Bluetooth Speaker",
    description: "Portable speaker with exceptional sound quality",
    price: 75,
    category: "electronics",
  },
  {
    id: 14,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP1CPGyZ7xZq1zH-pNW5sdjZuzOHvsf5_F1g&usqp=CAU",
    title: "Classic Jeans",
    description: "Timeless and durable denim jeans",
    price: 45,
    category: "clothing",
  },
  {
    id: 15,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXzltS2wgxELCCRKxQR4Vv5IapB7I65acnvq_hJCV5BUM73NvIFkBYPCpPjzRJBzWjBTo&usqp=CAU",
    title: "High-Speed Blender",
    description: "Efficient blender for smoothies and soups",
    price: 80,
    category: "home and kitchen appliances",
  },
  {
    id: 16,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIbUViLnLpr2zoH5vvN6rIsQJONKApIiVKbg&usqp=CAU",
    title: "Matte Lipstick",
    description: "Long-lasting and vibrant matte lipstick",
    price: 12,
    category: "health and beauty",
  },
  {
    id: 17,
    img: "https://lmsin.net/cdn-cgi/image/h=750,w=750,q=85,fit=cover/https://aaeff43fe32172cbcecc-ae2a4e9a8cbc330ede5588dedf56886e.lmsin.net/homecentre/1000012656760-1000012656759_01-2100.jpg",
    title: "Coffee Table",
    description: "Modern and stylish coffee table for your space",
    price: 150,
    category: "furniture and home decor",
  },
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/51Cnz31VyOL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Toolbox Set",
    description: "Complete set of tools for DIY enthusiasts",
    price: 65,
    category: "automotive and tools",
  },
  {
    id: 19,
    img: "https://ik.imagekit.io/panmac/tr:f-auto,w-740,pr-true//bcd02f72-b50c-0179-8b4b-5e44f5340bd4/f6a72868-7079-4551-92c6-480c6a0080d4/Best-sci-fi-books.jpg",
    title: "Sci-Fi Book",
    description: "Imaginative science fiction book for enthusiasts",
    price: 18,
    category: "books and media",
  },
  {
    id: 20,
    img: "https://m.media-amazon.com/images/I/81qIMdpdY1L.jpg",
    title: "1000-Piece Puzzle",
    description: "Challenging puzzle for hours of entertainment",
    price: 25,
    category: "toys and games",
  },
  {
    id: 21,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiAdTEHbd-el9C0wSG1ogOWi2UT-hwuZj3jg&usqp=CAU",
    title: "Hiking Boots",
    description: "Durable boots for outdoor adventures",
    price: 90,
    category: "sports and outdoors",
  },
  {
    id: 22,
    img: "https://images.cltstatic.com/media/product/350/AE01021-SS0000-infinite-possibilities-earrings-in-rhodium-plated--silver-prd-5-pd.jpg",
    title: "Silver Earrings",
    description: "Elegant silver earrings for a touch of sophistication",
    price: 30,
    category: "jewelry and accessories",
  },
  {
    id: 23,
    img: "https://img1.exportersindia.com/product_images/bc-full/2019/7/1858761/hedge-trimmer-1562736810-4990252.jpeg",
    title: "Hedge Trimmer",
    description: "Efficient tool for trimming hedges and bushes",
    price: 70,
    category: "gardening and outdoor living",
  },
  {
    id: 24,
    img: "https://m.media-amazon.com/images/I/71EksVtWTdL._SL1500_.jpg",
    title: "Interactive Cat Toy",
    description: "Keeps your feline friend entertained and active",
    price: 15,
    category: "pet supplies",
  },
  {
    id: 25,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiH1A1LWyCC4l3j3FnrTXqND2M74rdbo9I2Q&usqp=CAU",
    title: "Smartwatch",
    description: "Multi-functional smartwatch with health tracking features",
    price: 150,
    category: "electronics",
  },
  {
    id: 26,
    img: "https://webmerx.sgp1.cdn.digitaloceanspaces.com/goldenbiz/product_images/GbmI2QSchq-1686220746-1.webp",
    title: "Evening Dress",
    description: "Elegant evening dress for special occasions",
    price: 80,
    category: "clothing",
  },
  {
    id: 27,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV00WTPta0UV7hkWAuui1agvBB9D076GMt8g&usqp=CAU",
    title: "Air Fryer",
    description: "Healthy cooking with an efficient air fryer",
    price: 100,
    category: "home and kitchen appliances",
  },
  {
    id: 28,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJmnhMV4NBOv1QCo6OhT7aBk7dlBx6rTH1aQ&usqp=CAU",
    title: "Facial Mask",
    description: "Hydrating and rejuvenating facial mask",
    price: 10,
    category: "health and beauty",
  },
  {
    id: 29,
    img: "https://www.jiomart.com/images/product/original/rvmwnprpyk/jeffry-engineered-wood-5-tier-floor-standing-bookcase-bookshelf-with-5-shelves-in-living-room-office-walnut-d-i-y-product-images-orvmwnprpyk-p602966304-0-202307052216.jpg?im=Resize=(420,420)",
    title: "Bookshelf",
    description: "Sturdy and spacious bookshelf for your home",
    price: 120,
    category: "furniture and home decor",
  },
  {
    id: 30,
    img: "https://m.media-amazon.com/images/I/51c92e6wH0L._SY300_SX300_QL70_FMwebp_.jpg",
    title: "Socket Wrench Set",
    description: "Versatile set for various mechanical tasks",
    price: 50,
    category: "automotive and tools",
  },
  {
    id: 31,
    img: "https://m.media-amazon.com/images/I/51SHzt1GYcL._SX342_SY445_.jpg",
    title: "Cookbook",
    description: "Delicious recipes for every occasion",
    price: 25,
    category: "books and media",
  },
  {
    id: 32,
    img: "https://m.media-amazon.com/images/I/61xKK6fHQeL._SL1000_.jpg",
    title: "Action Figure",
    description: "Collectible action figure for fans",
    price: 15,
    category: "toys and games",
  },
  {
    id: 33,
    img: "https://media.trekbikes.com/image/upload/f_auto,fl_progressive:semi,q_auto,w_1440,h_1080,c_pad/FuelEX5Deore_22_33073_B_Portrait",
    title: "Mountain Bike",
    description: "Durable mountain bike for outdoor adventures",
    price: 300,
    category: "sports and outdoors",
  },
  {
    id: 34,
    img: "https://5.imimg.com/data5/SELLER/Default/2022/10/XZ/KT/ET/11865648/84f434ff-d6f0-407c-be48-0138f8766f16-500x500.JPEG",
    title: "Anklet",
    description: "Stylish anklet to accessorize your look",
    price: 18,
    category: "jewelry and accessories",
  },
];
export default productsData;
